Add test script, ensure gradle runs from root

diff --git a/bin/ncu b/bin/ncu
--- a/bin/ncu
+++ b/bin/ncu
@@ -16,12 +16,23 @@
 # limitations under the License.
 #
 
+BINDIR="$(realpath "$(dirname "$0")")"
+ROOT="$(realpath "$(dirname "${BINDIR}")")"
+readonly ROOT
+unset BINDIR
+
 main() {
   if ! command -v npx >/dev/null; then
     printf -- 'You must install nodejs and npm\n'
     return 1
   fi
-  
+
+  # Gradle commands must be run from root
+  cd "${ROOT}" || {
+    printf -- 'Failed to cd into gradle root: %s\n' "${ROOT}"
+    return 1
+  }
+
   npx ncu -u || return 1
   npm up || return 1
   return 0
@@ -29,5 +40,3 @@ main() {
 
 main "$@" || exit 1
 exit 0
-
-
